name: test build
on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v6

      - name: Install Bun
        uses: oven-sh/setup-bun@v2

      - name: Run it
        run: bun install && bun run build
